### ISSUE TITLE
links to reach the train recurrent variational network are expired. 

### ISSUE THREAD

**Issue by finger1517** [NKI-AI/direct#154]
links to reach the train recurrent variational network (both 5x and 10x) are expired.

**Comment by finger1517** [comment]
in addition, a lot of link are not available, please check Markdown documents

**Comment by jonasteuwen** [comment]
Could you give a little bit more details please? All the links here seem to work: https://github.com/NKI-AI/direct/blob/main/model_zoo.md (except the first two it seems)

**Comment by finger1517** [comment]
> Could you give a little bit more details please? All the links here seem to work: https://github.com/NKI-AI/direct/blob/main/model_zoo.md (except the first two, but they will be added.)

haha, if you do not include the first two, the links are all perfect, 

if you add (to be upload) after first two models, it will be a good instruction for us to know that it is has not been uploaded.

**Comment by georgeyiasemis** [comment]
Closed with https://github.com/NKI-AI/direct/commit/d874e8d983dd854f086c45844136cfdef3925342.
