### ISSUE TITLE
URGING FOR GOOD TUTORIALS

### ISSUE THREAD

**Issue by finger1517** [NKI-AI/direct#155]
HEY THERE, I appreciated that you give such a complete open source mri reconstruction tool for us, the APIs are well defined, and the models are up-to-date.

But I was confused that  I learn the toolbox by bottomed up ways, and there are no such good tutorials for us. I think a good way to make your work perfect is to provide concise and Easy-understand jupyternotebook tutorials for how to train new models and how to use pretrained models for fast reconstruction[both for single patients and for some datasets]

I will appreciate it if you can accomplish the tutorials and hope your work will be the standard for the deep learning mri reconstruction toolbox.

If you can provide the tutorials personally, please send me a copy, my email is finger1517@163.com.

BEST WISHES,
AYUAN YANG.

**Comment by georgeyiasemis** [comment]
Hi Ayuan @finger1517. We are in the process of updating DIRECT, and therefore the documentation. We'll make sure to provide adequate documentation. Thanks for letting us know!

**Comment by jonasteuwen** [comment]
Hi @finger1517 we added documentation and improved the release: https://docs.aiforoncology.nl/direct. Happy computing ;-)
