### ISSUE TITLE
Reduce pylint and mypy warnings

### ISSUE THREAD

**Issue by jonasteuwen** [NKI-AI/direct#158]
**Is your feature request related to a problem? Please describe.**
Current code base disables anything but mypy/pylint errors. Needs to have a 100% pass rate

**Describe the solution you'd like**
100% pass rate of mypy and pylint.

**Comment by georgeyiasemis** [comment]
Need to also remove all **assert_complex** tests and make it explicit, maybe by specifying `complex_axis`.
