### ISSUE TITLE
Problems building docker image

### ISSUE THREAD

**Issue by estenhl** [NKI-AI/direct#191]
Unable to build the docker image on both Ubuntu and macOS due to what seems like multiple errors

**To Reproduce**
````
> docker build -t direct:latest .
Sending build context to Docker daemon  6.144kB
Error response from daemon: dockerfile parse error line 21: unknown instruction: &&
````
Fixed by adding backslashes to lines 20-24
````
 => ERROR [10/15] RUN jupyter notebook --generate-config                   0.3s
------
 > [10/15] RUN jupyter notebook --generate-config:
#14 0.259 /bin/sh: 1: jupyter: not found
````
Fixed by adding a line for conda installing jupyter
````
 => ERROR [14/15] RUN python -m pip install -e ".[dev]"                    1.2s
------                                                                          
 > [14/15] RUN python -m pip install -e ".[dev]":
#18 0.890 ERROR: File "setup.py" or "setup.cfg" not found. Directory cannot be installed in editable mode: /direct
````
Wasn't able to get to the bottom of this one

**Environment**
Operating system: Ubuntu 18.04.5 LTS
Docker version: 20.10.14

and 

Operating system: macOS Monterey 12.2.1
Docker version: 20.10.8

**Comment by georgeyiasemis** [comment]
Hi @estenhl, can you follow the instructions using `conda` (https://docs.aiforoncology.nl/direct/installation.html#install-using-conda), as we try to solve the above issue?

**Comment by sairamgeethanath** [comment]
@georgeyiasemis I think lines 20 through 24 are missing new line characters (\)

RUN git clone https://github.com/mrirecon/bart.git /tmp/bart
    && cd /tmp/bart
    && make -j4
    && make install
    && rm -rf /tmp/bart

**Comment by Winnie-xwj** [comment]
I have used the Conda instructions(https://docs.aiforoncology.nl/direct/installation.html#install-using-conda) and worker with Colab, but I have some problems in reproducing the experiment in their paper (Recurrent Variational Network: A Deep Learning Inverse Problem Solver applied to the task of Accelerated MRI Reconstruction (CVPR 2022)[¶](https://docs.aiforoncology.nl/direct/cvpr2022_recurrentvarnet.html#recurrent-variational-network-a-deep-learning-inverse-problem-solver-applied-to-the-task-of-accelerated-mri-reconstruction-cvpr-2022)
<img width="1326" alt="截屏2022-05-03 下午9 07 14" src="https://user-images.githubusercontent.com/82263365/166462425-f937eb8f-e973-4b32-818a-5168205907f5.png">
Could you give me some advice?
