### ISSUE TITLE
how to support 1-channel unet?

### ISSUE THREAD

**Issue by kingaza** [NKI-AI/direct#200]
The input and target for the model are the under-sampled and full-sampled images respectively.
So the forward_operator and backward_operator are not needed.

**Comment by georgeyiasemis** [comment]
Hi @kingaza. Supporting only images  is outside of the scope of this project as MRI data are k-space data acquired from single or multiple receiver coils which are transformed to imaged through the ifft. So having as input already reconstructed images is not in the scope of DIRECT.

However,  if you can elaborate more on the kind of data and what you want to do, maybe I can help you find a solution.
