### ISSUE TITLE
Having troubles in reproducing the experiment on Recurrent Variational Network: A Deep Learning Inverse Problem Solver applied to the task of Accelerated MRI Reconstruction (CVPR 2022)

### ISSUE THREAD

**Issue by Winnie-xwj** [NKI-AI/direct#201]
I have followed the instructions on the https://docs.aiforoncology.nl/direct/colab.html and successfully installed the 'direct'. Then, according to project folder https://docs.aiforoncology.nl/direct/cvpr2022_recurrentvarnet.html, I pasted the command to Colab, but there is still something wrong.
<img width="1326" alt="截屏2022-05-03 下午9 07 14" src="https://user-images.githubusercontent.com/82263365/166458402-cabb9d25-25fe-4f1e-aa45-6da0ea7aab64.png">

**Comment by georgeyiasemis** [comment]
Hi @Winnie-xwj, the command you are running seems wrong. The correct usage is as follows:

```python

direct train <PATH_TO_TRAINING_DATA_DIRECTORY>  <PATH_TO_VAL_DATA_DIRECTORY> <experiment_directory> --num-gpus <number_of_gpus> --cfg <path_or_url_to_yaml_file> [--other-flags]

```

**Comment by georgeyiasemis** [comment]
* To dowload the Multi_Channel Calgary Campinas Dataset check out: https://portal.conp.ca/dataset?id=projects/calgary-campinas
* To see how to run experiments using DIRECT check out: https://docs.aiforoncology.nl/direct/training.html
* To reproduce experiments for the RecurrentVarNet paper check out https://docs.aiforoncology.nl/direct/cvpr2022_recurrentvarnet.html
