### ISSUE TITLE
is it possible to use your tool for denoising and resampling dicom data?

### ISSUE THREAD

**Issue by jakubMitura14** [NKI-AI/direct#214]
Hello thanks for publishing fantastic work, 
s it possible to use this algorithm for dicom data (I do not have access to raw format)  
is it possible to resample data to different size using your algorithm - I want to resize the images from multiple modalities in prostate MRI to single array size in order to interpolate them but I would like to avoid the interpolation artifacts related to b spline method, so in principle If I understand correctly one could sample function approximating denoised signal at different resolution than original - am I correct?

Thank you for response !

**Comment by georgeyiasemis** [comment]
> is it possible to use this algorithm for dicom data (I do not have access to raw format) is it possible to resample data to different size using your algorithm

Hi @jakubMitura14. Unfortunately DIRECT does not support DICOM data, but it allows for flexicle implementation of your own PyTorch Datasets. Please check documentation!

**Comment by georgeyiasemis** [comment]
> I want to resize the images from multiple modalities in prostate MRI to single array size in order to interpolate them but I would like to avoid the interpolation artifacts related to b spline method, so in principle If I understand correctly one could sample function approximating denoised signal at different resolution than original - am I correct?

My apologies, but I am not sure we can help you with this question or how it's related to DIRECT.

**Comment by jakubMitura14** [comment]
Thank you for your response !
