### ISSUE TITLE
more trained model in zoo?

### ISSUE THREAD

**Issue by kingaza** [NKI-AI/direct#215]
hi,

Will the new trained model, like radial sampling, be submitted to Zoo?
As these model need lot of computation resources...

Best Regards,
king

**Comment by georgeyiasemis** [comment]
Hi @kingaza, I will try to upload our models used in our paper "Deep MRI Reconstruction with Radial Subsampling" (https://doi.org/10.1117/12.2609876) in model zoo.  It includes two RIMS trained on radial subsampling and rectilinear (random) subsampling.

**Comment by kingaza** [comment]
Thank you for your response!
