### ISSUE TITLE
Openvivo fft implementation causes backpropagation issues

### ISSUE THREAD

**Issue by georgeyiasemis** [NKI-AI/direct#219]
**Describe the bug**
Running a model **without** an additional model for sensitivity maps causes the following issue:
`NotImplementedError: You must implement either the backward or vjp method for your custom autograd.Function to use it with backward mode AD.`

**To Reproduce**
Running a model **without** an additional model for sensitivity maps.

**Expected behavior**
Not to get the error.

**Additional context**
Remove openvivo functionality, inspect later.

**Comment by likholat** [comment]
Hello, @georgeyiasemis
Could you please help me to reproduce this error? I can't find this case in tests for any 'RIM' or 'Unet2d' model.
