### ISSUE TITLE
Can it run in Windows OS environment?

### ISSUE THREAD

**Issue by gusrbgks** [NKI-AI/direct#231]
I would like to try Direct Toolkit in Windows OS environment. However, I encountered a problem during the installation and environment setting process, and I am contacting you because it seems to be a Linux-only tool. Thank you for your reply.

**Comment by georgeyiasemis** [comment]
I would suggest installing Windows Subsystem for Linux (WSL2). 
Take a look here for instructions https://learn.microsoft.com/en-us/windows/wsl/install

**Comment by NayeeC** [comment]
Hi @gusrbgks 
I run the code in Windows but can use one GPU only.
Try the modification in `environment.py`:
```
self.add_argument(
            "--dist-url",
            # default=f"tcp://127.0.0.1:{port}",
            default='auto',
            help="initialization URL for pytorch distributed backend. See "
            "https://pytorch.org/docs/stable/distributed.html for details.",
        )
```
You can find this path under the `class Args`

**Comment by jonasteuwen** [comment]
@NayeeC Can you provide a PR how to make it run under windows? A few lines of information for the documentation here would also be useful

**Comment by NayeeC** [comment]
Hi @jonasteuwen!
 My method only works under single GPU condition and seems a little bit hard, I'm afraid that my method is not a good PR
