### ISSUE TITLE
The .so file can be recognized

### ISSUE THREAD

**Issue by NayeeC** [NKI-AI/direct#234]
Hi!

I tried to run the code on Linux OS and followed the [instruction](https://docs.aiforoncology.nl/direct/) to run 'python setup.py install'. Two new files created by this command are `_gaussian.cypthon-38-x86_64-linux-gnu.so` and `_poisson.cypthon-38-x86_64-linux-gnu.so`. However, the 'subsample.py' can not import these two files correctly. The structure of the folder and file is like below:
```
direct
   |- build
      |- lib.linux-x86_64-cpython-38
      |- temp.linux-x86_64-cpython-38
   |- direct
      |- common
         |- __init__.py
         |- _gaussian..cypthon-38-x86_64-linux-gnu.so
         |- _gaussian.pyx
         |- _poisson.cypthon-38-x86_64-linux-gnu.so
         |- _poisson.pyx
         |- subsample.py
         |- subsample_config.py
```
And the code goes wrong in `subsample.py`:
```
from direct.common._gaussian import gaussian_mask_1d
from direct.common._poisson import poisson
```
The error is:
```
cannot find reference `_gaussian` in `__init__.py`
cannot find reference `_poisson` in `__init__.py`
```
The environment is :
```
Ubuntu=16.04.12
python=3.8
cuda=11.6
```
How should I solve this problem? Thank you for answering in advance.

BTW, I run `python setup.py install` in **Windows OS** and generated `.pyd` files. The import error does not exist in this situation.

**Comment by georgeyiasemis** [comment]
Hi @NayeeC. 

Could you try:

```make clean```

and then try to install again using

``` python3 -m pip install -e ".[dev]"```

**Comment by NayeeC** [comment]
I put the new structure below:
direct
   |- direct
      |- common
         |- __init__.py
         |- _gaussian.cypthon-38-x86_64-linux-gnu.so
         |- _gaussian.c
         |- _gaussian.pyx
         |- _poisson.cypthon-38-x86_64-linux-gnu.so
         |- _poisson.c
         |- _poisson.pyx
         |- subsample.py
         |- subsample_config.py
   |- setup.py

**Comment by georgeyiasemis** [comment]
> > python3 -m pip install -e ".[dev]"
> 
> Hi @georgeyiasemis I am sorry that this method does not work. I create another conda environment with `python=3.8` and use that environment in pycharm. Then I run the code above in the terminal after activating the new environment. The installation process seems good, there is no error occurring. But '_gaussian' is still unable to be imported. It occurs the same error in `subsample.py` and the structure of the folder and file is the same as in my last post. These were done in Linux.

@NayeeC I believe it must be your pycharm interpreter settings.

To check this, in an Ubuntu prompt, try first activating your environment, and then type `python3` to open up python, and then try 
```from direct.common._poisson import poisson```

**Comment by NayeeC** [comment]
> > > python3 -m pip install -e ".[dev]"
> > 
> > 
> > Hi @georgeyiasemis I am sorry that this method does not work. I create another conda environment with `python=3.8` and use that environment in pycharm. Then I run the code above in the terminal after activating the new environment. The installation process seems good, there is no error occurring. But '_gaussian' is still unable to be imported. It occurs the same error in `subsample.py` and the structure of the folder and file is the same as in my last post. These were done in Linux.
> 
> @NayeeC I believe it must be your pycharm interpreter settings.
> 
> To check this, in an Ubuntu prompt, try first activating your environment, and then type `python3` to open up python, and then try `from direct.common._poisson import poisson` or `from direct.common.subsample import *`

Hi @georgeyiasemis You are right! It did work in the terminal. Although I still don't know why the error occurs in Pycharm, but I find a way to solve the problem, just add the code below before `from direct.common._poisson import poisson`:
```
import sys
sys.path.insert(0, <.so file path>)
```
If the `.so` and the `.py` are in the same directory, as my case, the `<.so file paht>` will be `'_gaussian.cypthon-38-x86_64-linux-gnu.so'`. 

Thank you for your prompt response and really appreciate the work you've done!
