### ISSUE TITLE
Key 'list' not in CalgaryCompinasConfig

### ISSUE THREAD

**Issue by zwep** [NKI-AI/direct#248]
**Describe the bug**
Using a fresh installation of the package, after following the instructions [mentioned](https://docs.aiforoncology.nl/direct/installation.html), and downloading the pretrained [unet](https://s3.aiforoncology.nl/direct-project/unet.zip) I wanted to run the config file provided by the trained unet by running the following .

```
data_root='/this/is/empty/on/purpose'
result_path='~/results'
experiment_dir='~/pretrained_networks/direct/unet'
chpt_path='~/direct/unet/model_6000.pt'

python3 predict_val.py $result_path --checkpoint $chpt_path --experiment-directory $experiment_dir --data-root $data_root  --validation-index 0
```

but I get the following error

```
omegaconf.errors.ConfigKeyError: Key 'lists' not in 'CalgaryCampinasConfig'
    full_key: inference.dataset.lists
    reference_type=DatasetConfig
    object_type=CalgaryCampinasConfig

```

**To Reproduce**
Follow the steps to install the direct package with conda
Download the pretrained unet model
Change the paths to your system
Run the code above

**Expected behavior**

**Environment**
dlup version: Not installed. 
direct version: 1.0.5.dev0
How installed: using conda
Python version: 3.9
Operating System:
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye

**Additional context**
None

**Comment by georgeyiasemis** [comment]
You can replace `lists` with `filenames_lists`.
