### ISSUE TITLE
Data-consistency after test

### ISSUE THREAD

**Issue by yilmazkorkmaz1** [NKI-AI/direct#251]
Hi,

Thanks for this awesome repo!

I searched the codebase but could not find anything related to post data-consistency. 

I wonder whether you applied data-consistency after getting reconstructions from baselines, before calculating metrics, for the Calgary-Campinas challenge numbers that you reported in https://docs.aiforoncology.nl/direct/model_zoo.html.

**Comment by georgeyiasemis** [comment]
Hi @yilmazkorkmaz1.

No data consistency was applied, but you can easily implement that in the forward_function of the engine of any model

**Comment by yilmazkorkmaz1** [comment]
Sure, just wanted to know to compare numbers that I have.

Thanks!
