### ISSUE TITLE
[Implementation question] XPDnet

### ISSUE THREAD

**Issue by zwep** [NKI-AI/direct#253]
Sorry for not sticking to the Issue convention. I am a little bit hesitant to ask for help like this, because I think Im making a silly mistake somewhere... But Im curious if you can remark on the implementation of the CrossDomainNetwork class.

There, in the kspace_correction method of the CrossDomainNetwork class, I see the following update

```
            kspace_buffer = torch.cat([kspace_buffer, forward_buffer, masked_kspace], self._complex_dim)

            ...

            kspace_buffer = kspace_buffer[..., :2] - kspace_buffer[..., 2:4]
```

I have read the paper on the DPHG algorithm (https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=8271999) and the XPDNet (https://arxiv.org/pdf/2010.07290.pdf), but I couldnt see where this difference is coming from.

If I understand it correctly, we are taking the difference between the kspace_buffer (== initial kspace at the first iteration) and the forward_buffer (==kspace transformed from image space input at the first iteration). So this would end up being a very noisy image, since both the kspace_buffer and forward_buffer are very similar, if not identical. And even if this is not the case for the first iteration, my understanding is that ultimately the kspace_buffer and forward_buffer should start to convergence to each other.

How does this then become an appropriate input for the image_correction method?  I believe that I am making an error somewhere with the interpretation of the variables, but I cannot see my error at this point. So maybe one of you can help me with this. If you think responding this will take too much time please say so, then I'll think some more about it

**Comment by zwep** [comment]
I closed this because the numerical experiments showed at least proper image creation. So in practice it works fine I guess? But I am not able (limited time as well) to explain it why it works the way it does.

**Comment by georgeyiasemis** [comment]
Hi @zwep. Thanks for opening this. ATM I am not sure I fully understand your question, but in the next weeks I will try to go through the code to see if there is indeed some bug, or something.

A few notes:
* `_backward_operator` and `_forward operator` should **not** result in the identity. They are adjoints, not inverses. In accelerated MRI, an inverse to the forward operator does not exist (ill-posed problem due to sub-sampling).
* Code for `XPDNet` was adapted from https://github.com/zaccharieramzi/fastmri-reproducible-benchmark/blob/master/fastmri_recon/models/subclassed_models/cross_domain.py.

Hope the above helps

**Comment by zwep** [comment]
Ah okay, then I will try to make my question a bit more clear. Also thanks for the remark on the difference between the inverse/adjoint, you are completely correct in that of course. I will rewrite that question and replace the operator F(..., S, M) with the forward operator A (and similar for the adjoint A*).

To be precise, my question is about this piece of code


```
  def kspace_correction(
        self,
        block_idx: int,
        image_buffer: torch.Tensor,
        kspace_buffer: torch.Tensor,
        sampling_mask: torch.Tensor,
        sensitivity_map: torch.Tensor,
        masked_kspace: torch.Tensor,
    ) -> torch.Tensor:
        ...
        kspace_buffer = torch.cat([kspace_buffer, forward_buffer, masked_kspace], self._complex_dim)

        if self.kspace_model_list is not None:
            kspace_buffer = self.kspace_model_list[block_idx](kspace_buffer.permute(0, 1, 4, 2, 3)).permute(
                0, 1, 3, 4, 2
            )
        else:
            kspace_buffer = kspace_buffer[..., :2] - kspace_buffer[..., 2:4]

        return kspace_buffer
```

And then in particular the difference between `kspace_buffer[..., :2]' and `kspace_buffer[..., 2:4]'. I dont fully understand why the difference is used here. I tried to find this in the original paper but couldnt since there they use a specific k-space refinement network in their algorithm. I thought maybe it would act as some data consistency term but I dont see how that works with this implementation . Or that it should act as some form of residual learning, but since this residual is not the input to any network I also dont see how that could work

In the github page you linked I also looked at their implementation, but I don't see an alternative option to not using the k-space refinement module that you have.

There is no immediate rush with this, I can understand that you have more important priorities

**Comment by zwep** [comment]
Ah okay thanks, I get it. The goal is really to use the residual of the k-space. I thought that the k-space refinement stage should eventually produce an estimate of the fullly sampled k-space.... but I think I understand now why approximating the residual can also be useful
